"""
Slice Gemini_Generated_Image_3jlj7k3jlj7k3jlj.png into individual sprite files.
Detected coordinates via pixel analysis of the 2304x1842 source image.
"""
from PIL import Image
import os

SRC  = "Gemini_Generated_Image_3jlj7k3jlj7k3jlj.png"
img  = Image.open(SRC).convert("RGBA")
print(f"Source: {img.size}")

os.makedirs("assets/sprites", exist_ok=True)
os.makedirs("assets/icons",   exist_ok=True)
os.makedirs("assets/preview", exist_ok=True)   # for visual check

W, H = 72, 64  # final sprite size


def save(box, path, size=(W, H)):
    x0, y0, x1, y1 = box
    # Add 4px padding to catch edges, clamp to image bounds
    x0p = max(0, x0 - 4)
    y0p = max(0, y0 - 4)
    x1p = min(img.width,  x1 + 4)
    y1p = min(img.height, y1 + 4)
    crop = img.crop((x0p, y0p, x1p, y1p)).resize(size, Image.LANCZOS)
    crop.save(path)


# ── IDLE: 12 frames (4 per row, 3 rows) ──────────────────────────────────────
#
# Detected sprite x-positions per row (5 per row, we take 4):
#   Row 1 y=113-343 : x=79-310, 412-638, 720-965, 1061-1291   [idle 1-4]
#   Row 2 y=447-676 : x=83-316, 405-641, 736-968, 1058-1282   [idle 5-8]
#   Row 3 y=771-1011: x=82-312, 404-636, 724-950, 1050-1263   [idle 9-12]
#
idle_rows = [
    (113, 343, [(79,310),(412,638),(720,965),(1061,1291)]),
    (447, 676, [(83,316),(405,641),(736,968),(1058,1282)]),
    (771,1011, [(82,312),(404,636),(724,950),(1050,1263)]),
]
n = 1
for y0, y1, xs in idle_rows:
    for x0, x1 in xs:
        save((x0, y0, x1, y1), f"assets/sprites/idle_{n}.png")
        n += 1
print(f"idle: {n-1} frames")

# ── SLEEPING: 5 frames (3 yawning + 2 curled) ────────────────────────────────
#
# Row 4 y=1190-1426, split left (sleep A) / right (sleep B):
#   Sleep A (3 frames): x=78-339, 382-636, 671-943
#   Sleep B (2 frames): x=1051-1340, 1411-1707
#
sy0, sy1 = 1190, 1426
sleep_xs = [(78,339),(382,636),(671,943),(1051,1340),(1411,1707)]
for n, (x0, x1) in enumerate(sleep_xs, 1):
    save((x0, sy0, x1, sy1), f"assets/sprites/sleeping_{n}.png")
print(f"sleeping: {len(sleep_xs)} frames")

# ── WALK LEFT: 4 frames, uniform grid x=60-1120 ──────────────────────────────
#
# Cats overlap (touching legs/tail) so blob-detect fails.
# Uniform 265px-wide frames fit the detected content boundary 60-1120.
#
wy0, wy1 = 1515, 1812
walk_l = [(60, 325), (325, 590), (590, 855), (855, 1120)]
for n, (x0, x1) in enumerate(walk_l, 1):
    save((x0, wy0, x1, wy1), f"assets/sprites/walk_left_{n}.png")
print("walk_left: 4 frames")

# ── WALK RIGHT: auto-flip from walk_left ─────────────────────────────────────
#
# Walk Right section (x=1200-1850) produced inconsistent frame spacing.
# Flipping walk_left is cleaner and avoids direction mismatch.
# (Replace with direct slices from x=1200-1850 if you prefer the generated art.)
#
for n in range(1, 5):
    fr = Image.open(f"assets/sprites/walk_left_{n}.png").transpose(Image.FLIP_LEFT_RIGHT)
    fr.save(f"assets/sprites/walk_right_{n}.png")
print("walk_right: 4 frames (flipped from walk_left)")

# ── ZZZ: keep programmatically generated (already in assets/sprites/) ─────────
# The blue floating-Z frames generated by generate_assets.py are fine.
# Uncomment block below to slice from the Gemini image instead.
#
# zzz_frames = [...]
# for n, box in enumerate(zzz_frames, 1):
#     save(box, f"assets/sprites/zzz_{n}.png", size=(32,32))

# ── TRAY ICON: from bottom-right sidebar ─────────────────────────────────────
#
# Estimated tray icon region: x=1870-2240, y=1175-1530 (cat face, large)
#
tray_box = (1870, 1175, 2240, 1530)
save(tray_box, "assets/icons/tray_icon.png", size=(64, 64))
t32 = Image.open("assets/icons/tray_icon.png").resize((32,32), Image.LANCZOS)
t32.save("assets/icons/tray_icon.ico", format="ICO", sizes=[(16,16),(32,32)])
print("tray icon: saved")

# ── PREVIEW: save contact sheet for quick visual check ───────────────────────
def make_preview():
    thumbs = []
    labels = (
        [f"idle_{i}" for i in range(1,13)] +
        [f"sleeping_{i}" for i in range(1,6)] +
        [f"walk_left_{i}" for i in range(1,5)] +
        [f"walk_right_{i}" for i in range(1,5)]
    )
    for lbl in labels:
        p = f"assets/sprites/{lbl}.png"
        if os.path.exists(p):
            thumbs.append((lbl, Image.open(p)))

    cols = 8
    rows = (len(thumbs) + cols - 1) // cols
    tw, th = 72*2, 64*2
    sheet = Image.new("RGBA", (cols*tw + 10, rows*(th+20) + 10), (50,50,50,255))
    for i, (lbl, t) in enumerate(thumbs):
        col = i % cols
        row = i // cols
        t2 = t.resize((tw, th), Image.NEAREST)
        sheet.paste(t2, (col*tw + 5, row*(th+20) + 5), t2)
    sheet.save("assets/preview/contact_sheet.png")
    print(f"Preview saved: assets/preview/contact_sheet.png  ({sheet.size})")

make_preview()
print("\nDone! Check assets/preview/contact_sheet.png")
